# Generated by Django 4.2.5 on 2023-09-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=200)),
                ('decs', models.TextField()),
            ],
        ),
    ]
